services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=drobe
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - .:/app # Mount the current directory for hot reloading
    command: air # Use air for hot reloading in development
    depends_on:
      - migrations
      - localstack
    networks:
      - drobe-network

  migrations:
    build:
      context: .
      dockerfile: cmd/migrations/Dockerfile
    command: ./main
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - drobe-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack:/etc/localstack/init/ready.d"
    networks:
      - drobe-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=drobe
    networks:
      - drobe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - drobe-network

networks:
  drobe-network:
    driver: bridge
