// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: inventory.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO inventory (id, owner_id, name, category, color, size, brand, location, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, owner_id, name, category, color, size, brand, location, created_at, updated_at
`

type CreateItemParams struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	Category  string
	Color     string
	Size      string
	Brand     string
	Location  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Category,
		arg.Color,
		arg.Size,
		arg.Brand,
		arg.Location,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Category,
		&i.Color,
		&i.Size,
		&i.Brand,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM inventory WHERE id = $1 AND owner_id = $2
`

type DeleteItemParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.Exec(ctx, deleteItem, arg.ID, arg.OwnerID)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, owner_id, name, category, color, size, brand, location, created_at, updated_at FROM inventory WHERE id = $1 AND owner_id = $2
`

type GetItemByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getItemByID, arg.ID, arg.OwnerID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Category,
		&i.Color,
		&i.Size,
		&i.Brand,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, owner_id, name, category, color, size, brand, location, created_at, updated_at FROM inventory WHERE owner_id = $1
`

func (q *Queries) ListItems(ctx context.Context, ownerID pgtype.UUID) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listItems, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Category,
			&i.Color,
			&i.Size,
			&i.Brand,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemLocation = `-- name: UpdateItemLocation :exec
UPDATE inventory SET location = $2 WHERE id = $1 AND owner_id = $3
`

type UpdateItemLocationParams struct {
	ID       pgtype.UUID
	Location string
	OwnerID  pgtype.UUID
}

func (q *Queries) UpdateItemLocation(ctx context.Context, arg UpdateItemLocationParams) error {
	_, err := q.db.Exec(ctx, updateItemLocation, arg.ID, arg.Location, arg.OwnerID)
	return err
}
